@startuml
actor Admin
participant AdminController
participant AdminService
participant CommentRepository

Admin -> AdminController : click delete button
AdminController -> AdminService : deleteComment(id)
AdminService -> CommentRepository : deleteComment(id)
CommentRepository -> AdminService : return success (bool)
AdminService -> AdminController : return success (bool)
AdminController -> Admin : show success or error message
@enduml
