@startuml

left to right direction
skinparam actorStyle awesome
scale 3

actor "Utilisateur" as User
actor "Administrateur" as Admin

rectangle Blog {
    usecase "Lire des articles" as U1
    usecase "S'inscrire" as U2
    usecase "Se connecter" as U3
    usecase "Ajouter un commentaire" as U4
    usecase "Valider un commentaire" as U7
    usecase "Contacter l'Admin" as U8
    usecase "Ajouter un article" as U5
    usecase "Modifier un article" as U6
    usecase "Supprimer un article" as U9
}

User -down-> U1
User -down-> U2
User -down-> U3
User -down-> U4
User -down-> U5
User -down-> U6
User -down-> U8
User -down-> U9

Admin -down-> U1
Admin -down-> U3
Admin -down-> U4
Admin -down-> U6
Admin -down-> U7
Admin -down-> U9

U4 .> U3 : <<include>>
U5 .> U3 : <<include>>
U6 .> U3 : <<include>>
U7 .> U3 : <<include>>
U9 .> U3 : <<include>>

@enduml
