@startuml
actor Admin
participant AdminController
participant AdminService
participant UsersRepository

Admin -> AdminController : click approve button
AdminController -> AdminService : approveUser(id)
AdminService -> UsersRepository : confirmUser(id)
UsersRepository -> AdminService : return success (bool)
AdminService -> AdminController : return success (bool)
AdminController -> Admin : show success or error message
@enduml
