name: PHP_CodeSniffer

on:
  pull_request:
    branches:
      - '*'

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, xdebug

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-ansi --no-progress --no-suggest

      - name: Update Composer dependencies
        run: composer update

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs public/index.php src
